In [1]:
# description : This program detects if an email is spam(1) and or not(0)

In [3]:
#import libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [5]:
#load the data
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [6]:
# Read the csv file
df = pd.read_csv("emails.csv")

In [7]:
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [8]:
df.describe()

spam
count  5728.000000
mean      0.238827
std       0.426404
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [9]:
print(df.shape)

(5728, 2)


In [10]:
df.columns

Index(['text', 'spam'], dtype='object')

In [11]:
#check for duplicates
df.drop_duplicates(inplace=True)

In [12]:
df.shape


(5695, 2)

In [20]:
#show the number of missing data
df.isnull().sum()

text    0
spam    0
dtype: int64

In [21]:
#Download the stopwords package
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [24]:
def process_text(text):
  #1 remove the punctuation
  #2 remove stopwords
  #3 return the list of clean text words
  #1
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)
  
  #2
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
 
 #3
  return clean_words

In [25]:
#show the tokenization ( a list of tokens also called lememas)

In [26]:
df["text"].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [27]:
#example 
message4 = "hello world hello hello world play"
message5 = "test test test test one hello"
print(message4)
print()

hello world hello hello world play



In [28]:
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
bow4 = CountVectorizer(analyzer = process_text).fit_transform([[message4],[message5]])

In [32]:
print(bow4.shape)

(2, 5)


In [33]:
print(bow4)

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1


In [34]:
#convert a collection of text to matrix of token
messages_bow = CountVectorizer(analyzer = process_text).fit_transform(df["text"])

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(messages_bow,df["spam"],test_size = 0.20, random_state = 0)

In [36]:
messages_bow.shape

(5695, 37229)

In [39]:
#naive bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train,y_train)

In [44]:
print(classifier.predict(x_train))

[0 0 0 ... 0 0 0]


In [43]:
print(y_train.values)

[0 0 0 ... 0 0 0]


In [47]:
# evaluate
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

In [49]:
pred = classifier.predict(x_train)
print(classification_report(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556



In [50]:
print("confusion matrix",confusion_matrix(y_train,pred))

confusion matrix [[3445   12]
 [   1 1098]]


In [51]:
print("Accuracy",accuracy_score(y_train,pred))

Accuracy 0.9971466198419666


In [52]:
print(classifier.predict(x_test))

[1 0 0 ... 0 0 0]


In [53]:
print(y_test.values)

[1 0 0 ... 0 0 0]


In [54]:
pred = classifier.predict(x_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139



In [56]:
print("Accuracy",accuracy_score(y_test,pred))

Accuracy 0.9920983318700615
